version: '3.9'

services:
  api-service:
    container_name: api-container
    image: api-image
    build:
      context: -/
      dockerfile: Dockerfile
    env_file:
      - .env
#    environment:
    ports:
      - '8080:8080'
    networks:
      - backend
networks:
  backend:
    driver: bridge