version: '3.8'

services:
  api-service:
    container_name: skincare-products-sales-system
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/swd392-skincare-products-sales-system
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
    restart: always

  mysql:
    container_name: mysql
    image: mysql:8.0.41-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}  # Set root password
      MYSQL_DATABASE: "swd392-skincare-products-sales-system"  # Auto-create database
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: