server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1/swd392-skincare-products-sales-system}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://swd392-mysql-skincare.mysql.database.azure.com:3306/swd392-skincare-products-sales-system?useSSL=true&requireSSL=false&serverTimezone=UTC}
    username: ${DATASOURCE_USERNAME:crosoficelldan}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
open:
  api:
    title: API document
    version: v1.0.0
    description: API Service
    serverUrl: http://localhost:8080/api/v1/swd392-skincare-products-sales-system
    serverName: Server
    license: https://github.com/gahoccode215/Spring2025SWD392_NET1708_3
jwt:
  signerKey: ${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}
  valid-duration: ${JWT_VALID_DURATION:20} # in second
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:36000} # in seconds