server:
  port: 8080
  servlet:
    context-path: /api/v1/swd392-skincare-products-sales-system
spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/swd392-skincare-products-sales-system"
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
open:
  api:
    title: API document
    version: v1.0.0
    description: API Service
    serverUrl: http://localhost:8080/api/v1/swd392-skincare-products-sales-system
    serverName: Server
    license: https://github.com/gahoccode215/Spring2025SWD392_NET1708_3
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 20 # in second
  refreshable-duration: 36000 # in seconds