server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1/swd392-skincare-products-sales-system}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: caubenhatnhut@gmail.com
    password: nhatnhut123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #  data:
  #    redis:
  #      port: 6379
  #      host: localhost
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://${AZURE_DB_HOST:azure-mysql-fpt.mysql.database.azure.com}:${AZURE_DB_PORT:3306}/${AZURE_DB_NAME:swp391-skincare-products-sales-system}?useSSL=true&requireSSL=false&serverTimezone=UTC
    username: ${AZURE_DB_USERNAME:crosoficelldan}
    password: ${AZURE_DB_PASSWORD:Sokaboy215}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
open:
  api:
    title: API document
    version: v1.0.0
    description: API Service
    serverUrl: http://localhost:8080/api/v1/swd392-skincare-products-sales-system
    serverName: Server
    license: https://github.com/gahoccode215/Spring2025SWD392_NET1708_3

jwt:
  signerKey: ${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}
  valid-duration: ${JWT_VALID_DURATION:3600} # in seconds
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:36000} # in seconds
vnpay:
  tmnCode: M0R9Z6E1
  hashSecret: 6Z3AGDLVVDYXEAE3JKBNI6LN2ARZXXST
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/api/v1/swd392-skincare-products-sales-system/orders/payment-callback
postmark:
  api:
    key: ba355e86-7ee0-44c3-94fb-809826d15af5
  from:
    address: minhdlcnse173451@fpt.edu.vn
base:
  be:
    url: http://localhost:8080/api/v1/swd392-skincare-products-sales-system
  fe:
    url: http://localhost:5173